### ISSUE TITLE
发现个bug     配置agent.log.interval.seconds 间隔写log时间怎么加入到 整个请求时间上了

### ISSUE THREAD

**Issue by weiwang00707** [dingjs/javaagent#5]
作者你好
         我发现配置间隔写log时间6s，结果我的方法监控就多加上了6s
         怀疑这块有bug

**Comment by dingjs** [comment]
你好，方法监控多加上了6S是什么意思，麻烦说详细点

**Comment by weiwang00707** [comment]
这样的 方法执行只有一行 打印hello， 但是输出的json 显示 执行了6s
我怀疑是 间隔时间 处理到执行时间里面了

**Comment by weiwang00707** [comment]
eg:
	"class": "com.johnathanmsmith.mvc.web.controller.IndexController",
		"start": "2019-07-18 11:17:10",
		"end": "2019-07-18 11:17:16",

但是其实这个方法里面  只有一句输出hello  但是监控显示 执行了6s
刚好这个差值 跟agent.log.interval.seconds   的值是一样的

**Comment by dingjs** [comment]
你好，这个问题不存在哈，建议你尝试几次。我能想到的是你加了断点调试，确实是执行了6S。
你可以看看这个网址 http://47.96.150.36:8080，其他人的数据。
间隔时间没有算到执行时间里，这块代码是反复验证的。
